### ISSUE TITLE
Proposal: Encoding/Decoding

### ISSUE THREAD

**Issue by scrogson** [monterail/tesla#5]
In order to remove any specific JSON library dependencies, I'd like to propose a refactoring of the current implementation.

Have a look at how [`Plug.Parsers`](https://github.com/elixir-lang/plug/blob/master/lib/plug/parsers.ex#L38-L77) works. I think something similar can be done for `Tesla`.

Some pseudo code:

```elixir
with Tesla.Parser, parsers: [:json], accepts: ["application/json"], json_module: Poison
```

This would end up calling a callback module (`Tesla.Parsers.JSON`) passing in the the options and using `Poison` as the module to decode the response body.

Something similar could be done to handle encoding. Both `poison` and `exjsx` provide `encode!/1` functions.

Similar callback modules can be created to automatically encode/decode based on the `Content-Type`/`Accept` headers.

Just a thought, what do you think?

**Comment by teamon** [comment]
Decoupling form exjsx is definitely the way to go, but I would like to keep few "features".

### Separate encoder/decoder

There can be many variations of API, e.g one that takes parameters as form/url-encoded and returns JSON or XML, others that take XML or JSON as requests and returns some proprietary format etc.

### Nice API with good defaults

While flexibility is very important I think there still should be some default behaviour provided ootb, e.g. simple middleware `Tesla.Middleware.DecodeJson` that does not need any further configuration.

There is also a question, where the actual configuration should live. 
Given there are packages like:
- tesla - this library
- github-api - GitHub API wrapper built on top of tesla
- my-app - some application that uses github-api

Now, I believe it should be my-app's owner choice to select JSON parsing library. This would require some kind of configuration inside my-app like:
```ex
Tesla.Middleware.DecodeJson.backend = :poison # or :exjsx, etc
```
while still providing some default backend with proper error message when such backend library was included in dependencies.
